@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}
@version=v3
@attribute_value_id=1

//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values

###

//  Get All Customer Atribute Values
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesget
GET {{url}}/customers/attribute-values
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

###

//  Upsert Customer Attribute Value
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesput
PUT {{url}}/customers/attribute-values
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

[
  {
    "attribute_id": -52528392,
    "value": "aliqua",
    "customer_id": 12990306,
    "id": 47143304
  },
  {
    "attribute_id": -8263909,
    "value": "n",
    "customer_id": 1122433,
    "id": -34305734
  },
  {
    "attribute_id": -62186196,
    "value": "",
    "customer_id": 10906989,
    "id": 21175547
  },
  {
    "attribute_id": -68742149,
    "value": "l",
    "customer_id": -74084818,
    "id": 99359610
  }
]

###
//  Delete Customer Attribute Values
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesdelete
delete {{url}}/customers/attributes-values?id:in={{attribute_value_id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

