@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}
@version=v3
@attribute_value_id=1
@customer_id=77

//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values

###

//  Get All Customer Atribute Values
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesget
GET {{url}}/customers/attribute-values?customer_id:in={{customer_id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

###

//  Upsert Customer Attribute Value
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesput
PUT {{url}}/customers/attribute-values
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

[
  {
    "attribute_id": 3,
    "value": "100",
    "customer_id": 77
  }
]

###
//  Delete Customer Attribute Values
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customer-attribute-values/customersattributevaluesdelete
delete {{url}}/customers/attributes-values?id:in={{attribute_value_id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

