@version=v2
@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}
@customer_id=2

//  https://developer.bigcommerce.com/api-reference/store-management/customers-v2/customer-passwords/

###

//  Validate a password
//  https://developer.bigcommerce.com/api-reference/store-management/customers-v2/customer-passwords/validatecustomerpassword
POST {{url}}/customers/{{customer_id}}/validate
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "password": "abc12345"
}
