@url={{$dotenv STORE_DOMAIN}}/login/token/{{$dotenv GRAPHQL_TOKEN}}

//  https://developer.bigcommerce.com/api-reference/store-management/tokens

###

POST {{url}}
Content-Type: application/json

###

//  Revoke a token
//  https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken
DELETE {{url}}/storefront/api-token
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Sf-Api-Token: abc123abc123abc123abc123abc123abc123abc123