@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}
@version=v3
@id=21164010

//  https://developer.bigcommerce.com/api-reference/store-management/webhooks

###

//  Get All Webhooks
//  https://developer.bigcommerce.com/api-reference/store-management/webhooks/webhooks/getallwebhooks
GET {{url}}/hooks
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

###

//  Create a Webhook
//  https://developer.bigcommerce.com/api-reference/store-management/webhooks/webhooks/createwebhooks
POST {{url}}/hooks
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

{
  "scope": "store/cart/lineItem/*",
  "destination": "https://cart-stream.loca.lt/listen"
}

###

//  Get a Webhook
//  https://developer.bigcommerce.com/api-reference/store-management/webhooks/webhooks/getwebhook
GET {{url}}/hooks/{{id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

###

//  Update a Webhook
//  https://developer.bigcommerce.com/api-reference/store-management/webhooks/webhooks/updateawebhook
PUT {{url}}/hooks/{{id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json

{
  "scope": "store/cart/lineItem/*",
  "destination": "https://cart-stream.loca.lt/listen"
}

###
//  Delete a Webhook
//  https://developer.bigcommerce.com/api-reference/store-management/webhooks/webhooks/deleteawebhook
DELETE {{url}}/hooks/{{id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
