@version=v3
@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}

//  https://developer.bigcommerce.com/api-reference/store-management/tokens

###

//  Create a token
//  https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken
POST {{url}}/storefront/api-token
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json


{
  "channel_id": 1,
  "expires_at": 1609372800,
  "allowed_cors_origins": [
    "https://v3.bcdemoshop.com.au/"
  ]
}

###

//  Revoke a token
//  https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken
DELETE {{url}}/storefront/api-token
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Sf-Api-Token: abc123abc123abc123abc123abc123abc123abc123