@url={{$dotenv GRAPHQL_URL}}/graphql

//  https://developer.bigcommerce.com/api-reference/storefront/graphql

###

POST {{url}}
Authorization: Bearer {{$dotenv GRAPHQL_TOKEN}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login($email: String!, $pass: String!) {
  login(email: $email, password: $pass) {
    result
  }
}