
//  https://developer.bigcommerce.com/api-reference/storefront/graphql

###

POST {{$dotenv GRAPHQL_URL}}
Authorization: Bearer {{$dotenv GRAPHQL_TOKEN}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login($email: String!, $pass: String!) {
  login(email: $email, password: $pass) {
    result
  }
}

{
  "email": "{{$dotenv EMAIL}}", 
  "pass": "{{$dotenv PASS}}"
}