@version=v3
@url=https://api.bigcommerce.com/stores/{{$dotenv STORE_ID}}/{{version}}
@channel_id=594545

//  https://developer.bigcommerce.com/api-reference/store-management/channels/channels

###

//  Get All Channels
//  https://developer.bigcommerce.com/api-reference/store-management/channels/channels/listchannels
GET {{url}}/channels
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json

###
//  Get a Channel
//  https://developer.bigcommerce.com/api-reference/store-management/orders/orders/getanorder
GET {{url}}/channels/{{channel_id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json

###

//  Create an Channel
//  https://developer.bigcommerce.com/api-reference/store-management/channels/channels/createchannel
POST {{url}}/channels
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json

{
    "is_listable_from_ui": true,
    "is_visible": true,
    "external_id": "",
    "type": "storefront",
    "platform": "custom",
    "is_enabled": true,
    "name": "Next.js Stackbit Storefront"
}

###
//  Update a channel
//  https://developer.bigcommerce.com/api-reference/store-management/channels/channels/updatechannel
PUT {{url}}/channels/{{channel_id}}
X-Auth-token: {{$dotenv ACCESS_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "url": "https://nextjs-commerce-bcdemo.vercel.app"
}
